### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by weskerfoot** [nikolas/github-drama#105]
The maintainers appear to have abandoned this project. There are 10 unmerged PRs, come on!

**Comment by bullno1** [comment]
Let's make some drama here.

**Comment by nikolas** [comment]
Those are unmerged because they aren't funny enough.

**Comment by nikeee** [comment]
How about closing PRs that won't get merged anyways?

**Comment by nikolas** [comment]
Because I'm still thinking about them. I might change my mind.
