### ISSUE TITLE
I had to make this f*cking drama GRRRR FOR ORACLE

### ISSUE THREAD

**Issue by terremoth** [nikolas/github-drama#118]
https://github.com/mysql/mysql-workbench/pull/25

GRRRRRRRRR

**Comment by InCogNiTo124** [comment]
You know you could've just send them an email or something like a normal person would? This won't ever change their bug reporting, so the result is the same, but you wasted way more time and energy AND you now look like an angsty dork

**Comment by terremoth** [comment]
@InCogNiTo124 I think they gonna ignore me the same way.
They are full of shit.

Yes, I wasted energy and time. 
I just had to make an outburst about that.

**Comment by fredricj** [comment]
You care about submitting a bug report and they care about tracking it properly, preferably in one system. I prefer having one place to check if a bug is already reported.
Having multiple different places to submit and search for bugs is just horrible from a discoverability perspective.

**Comment by terremoth** [comment]
@fredricj I agree.
And the "one bug reporting system" could be in Github.
But the main problem is that they ask all about you and your life before you can just submit a bug.
