### ISSUE TITLE
Add node-ipc

### ISSUE THREAD

**Issue by MightyJosip** [nikolas/github-drama#133]
Drama issue: https://github.com/RIAEvangelist/node-ipc/issues/233

**Comment by woshiguabi** [comment]
-

**Comment by AndNovAtor** [comment]
Even "better" - [now] this issue was REMOVED from issues page. So, as it, it can't be added.

...some sort of archive page still can used (but not here?); for example, http://web.archive.org/web/20220408044442/https://github.com/RIAEvangelist/node-ipc/issues/233

**Comment by Dialga** [comment]
PR #134 opened.
