### ISSUE TITLE
active community-maintained fork after 2022

### ISSUE THREAD

**Issue by Lin2Jing4** [nikolas/github-drama#156]
The GitHub-drama community has forked and created a new repository in 2022 because the original maintainer is inactive.

The community-maintained fork is:
https://github.com/github-drama/github-drama

***We have merged all pull requests from the old repository into the new fork.***

In the new fork, all community members can edit collaboratively and enjoy a liberal editing policy similar to Wikipedia.

To edit, open a pull request in the community-maintained fork. **We will merge it as soon as we see the notification.**

To edit a large amount of content, open an issue and say so. **We will give you write access.**

**Comment by nikolas** [comment]
uhhh, okay.

**Comment by RIP-webmaster** [comment]
Why that repo gives 404 now? Removed or made private?

**Comment by hinell** [comment]
I guess, @nikolas will have to add this one repo as drama as well. We are having recurions now: drama on drama!

**Comment by MSDN-WhiteKnight** [comment]
I've created a mirror https://github.com/neodrama/github-drama with near-latest version to keep information available. I could take it down if the original repo is restored.

There's ongoing privacy drama at moq repo now, by the way: https://github.com/moq/moq/issues/1372

**Comment by hinell** [comment]
@ghost What matters? You could tell us more!

**Comment by nukeop** [comment]
In some of these cases it's as easy as just opening a support ticket, and deleting a single post somebody reported.

No idea why'd they ban an entire account instead of deleting the post themselves.
