### ISSUE TITLE
When you HTTParty, you must party hard

### ISSUE THREAD

**Issue by jayelm** [nikolas/github-drama#16]
https://github.com/jnunemaker/httparty/pull/321

People upset at HTTParty's post-install message:

```
   ~ : sudo gem install httparty
  Password:
  When you HTTParty, you must party hard!
  Successfully installed httparty-0.1.6
  1 gem installed
  Installing ri documentation for httparty-0.1.6...
  Installing RDoc documentation for httparty-0.1.6...
```

one of several other [1](https://github.com/jnunemaker/httparty/pull/388) [2](https://github.com/jnunemaker/httparty/pull/139) [3](https://github.com/jnunemaker/httparty/pull/211) [4](https://github.com/jnunemaker/httparty/pull/236) [5](https://github.com/jnunemaker/httparty/pull/237) [6](https://github.com/jnunemaker/httparty/pull/294) [7](https://github.com/jnunemaker/httparty/pull/315) independent, failed pull requests to remove the message, as well as other attempts to deal with the problem including [spinoffs](https://github.com/kristjan/httsoiree) and [more crude methods](https://github.com/tpope/gem-shut-the-fuck-up)

**Comment by Filia-Medici-x86-64** [comment]
i like the post install message
