### ISSUE TITLE
All the single clickers, put your hands up

### ISSUE THREAD

**Issue by jwoertink** [nikolas/github-drama#17]
https://github.com/atom/tree-view/pull/804

**Comment by bdoner** [comment]
Sadly it 404's by now :(

**Comment by timss** [comment]
You just need to remove the `s` from the URL:

https://github.com/atom/tree-view/pull/804

**Comment by dalexj** [comment]
🙌 🙌 🙌 🙌 🙌

**Comment by jacquesporveau** [comment]
10/10 would scoff again.

**Comment by nikolas** [comment]
added here - https://github.com/nikolas/github-drama/commit/06514b5f514877c3d37d2ead38516a16f2600003
