### ISSUE TITLE
Add Composer disable gc PR

### ISSUE THREAD

**Issue by SerafimArts** [nikolas/github-drama#23]
Subj: https://github.com/composer/composer/commit/ac676f47f7bbc619678a29deae097b6b0710b799

**Comment by nikolas** [comment]
thanks.. but looks like just a bunch of people making random comments, correct me if I'm wrong. This repo is strictly for high-drama discussions: https://github.com/nikolas/github-drama/blob/master/CONTRIBUTING.md
