### ISSUE TITLE
Add issue titles to list

### ISSUE THREAD

**Issue by philippTheCat** [nikolas/github-drama#85]
Seeing the issue titles in the list would make it a lot easier to see if this is drama that is interesting to me, or not

**Comment by nikolas** [comment]
Good idea!

**Comment by vaindil** [comment]
I'll have a lot of time today and can do a PR with this. I think it makes sense to keep it alphabetized as it is now, but add `: Title here` to the end of each line. Sound good?

**Comment by nikolas** [comment]
Yeah, sounds good

**Comment by nikolas** [comment]
Okay umm... pull requests welcome :P

For now i'm closing this.
